/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTransmissionRouteImport } from './routes/app.transmission'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppSendRouteImport } from './routes/app.send'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppCampaignsIndexRouteImport } from './routes/app.campaigns.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppCampaignsIdRouteImport } from './routes/app.campaigns.$id'
import { Route as AppAdminTemplatesRouteImport } from './routes/app.admin.templates'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppAdminErrorsRouteImport } from './routes/app.admin.errors'
import { Route as AppAdminDiagnosticsRouteImport } from './routes/app.admin.diagnostics'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransmissionRoute = AppTransmissionRouteImport.update({
  id: '/transmission',
  path: '/transmission',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTemplatesRoute = AppAdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminErrorsRoute = AppAdminErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDiagnosticsRoute = AppAdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/profile': typeof AppProfileRoute
  '/app/send': typeof AppSendRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/transmission': typeof AppTransmissionRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/diagnostics': typeof AppAdminDiagnosticsRoute
  '/app/admin/errors': typeof AppAdminErrorsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/templates': typeof AppAdminTemplatesRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/help': typeof AppHelpRoute
  '/app/profile': typeof AppProfileRoute
  '/app/send': typeof AppSendRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/transmission': typeof AppTransmissionRoute
  '/app': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/diagnostics': typeof AppAdminDiagnosticsRoute
  '/app/admin/errors': typeof AppAdminErrorsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/templates': typeof AppAdminTemplatesRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/campaigns': typeof AppCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/profile': typeof AppProfileRoute
  '/app/send': typeof AppSendRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/transmission': typeof AppTransmissionRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/diagnostics': typeof AppAdminDiagnosticsRoute
  '/app/admin/errors': typeof AppAdminErrorsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/templates': typeof AppAdminTemplatesRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/help'
    | '/app/profile'
    | '/app/send'
    | '/app/templates'
    | '/app/transmission'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/diagnostics'
    | '/app/admin/errors'
    | '/app/admin/settings'
    | '/app/admin/templates'
    | '/app/campaigns/$id'
    | '/app/admin/'
    | '/app/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/help'
    | '/app/profile'
    | '/app/send'
    | '/app/templates'
    | '/app/transmission'
    | '/app'
    | '/app/admin/audit'
    | '/app/admin/diagnostics'
    | '/app/admin/errors'
    | '/app/admin/settings'
    | '/app/admin/templates'
    | '/app/campaigns/$id'
    | '/app/admin'
    | '/app/campaigns'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/help'
    | '/app/profile'
    | '/app/send'
    | '/app/templates'
    | '/app/transmission'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/diagnostics'
    | '/app/admin/errors'
    | '/app/admin/settings'
    | '/app/admin/templates'
    | '/app/campaigns/$id'
    | '/app/admin/'
    | '/app/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transmission': {
      id: '/app/transmission'
      path: '/transmission'
      fullPath: '/app/transmission'
      preLoaderRoute: typeof AppTransmissionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/send': {
      id: '/app/send'
      path: '/send'
      fullPath: '/app/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns/': {
      id: '/app/campaigns/'
      path: '/campaigns'
      fullPath: '/app/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/campaigns/$id': {
      id: '/app/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/app/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/templates': {
      id: '/app/admin/templates'
      path: '/templates'
      fullPath: '/app/admin/templates'
      preLoaderRoute: typeof AppAdminTemplatesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/errors': {
      id: '/app/admin/errors'
      path: '/errors'
      fullPath: '/app/admin/errors'
      preLoaderRoute: typeof AppAdminErrorsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/diagnostics': {
      id: '/app/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/app/admin/diagnostics'
      preLoaderRoute: typeof AppAdminDiagnosticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminDiagnosticsRoute: typeof AppAdminDiagnosticsRoute
  AppAdminErrorsRoute: typeof AppAdminErrorsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminTemplatesRoute: typeof AppAdminTemplatesRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminDiagnosticsRoute: AppAdminDiagnosticsRoute,
  AppAdminErrorsRoute: AppAdminErrorsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminTemplatesRoute: AppAdminTemplatesRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppHelpRoute: typeof AppHelpRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSendRoute: typeof AppSendRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppTransmissionRoute: typeof AppTransmissionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppHelpRoute: AppHelpRoute,
  AppProfileRoute: AppProfileRoute,
  AppSendRoute: AppSendRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppTransmissionRoute: AppTransmissionRoute,
  AppIndexRoute: AppIndexRoute,
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
